"""
Fix notebooks:
  1. 02_bdd100k_preparation.ipynb - fix path detection bugs
  2. 01_dataset_setup_and_download.ipynb - add markdown explanations
"""
import json
import os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "notebooks")

# ============================================================
# PART 1: Fix 02_bdd100k_preparation.ipynb
# ============================================================
nb02_path = os.path.join(BASE, "02_bdd100k_preparation.ipynb")
with open(nb02_path, 'r', encoding='utf-8') as f:
    nb02 = json.load(f)

def clear_cell(cell):
    cell['outputs'] = []
    cell['execution_count'] = None

# --- Fix Cell 5: Path Configuration - add paths_config.yaml loading ---
nb02['cells'][5]['source'] = [
    "import os\n",
    "import sys\n",
    "import yaml\n",
    "\n",
    "# ── Path configuration ─────────────────────────────────────────────\n",
    "ECOCAR_ROOT = \"/content/drive/MyDrive/EcoCAR\"\n",
    "BDD_RAW_DIR = os.path.join(ECOCAR_ROOT, \"datasets\", \"bdd100k_raw\")\n",
    "\n",
    "# Where the YOLO-formatted dataset will be created\n",
    "YOLO_DATASET_DIR = os.path.join(ECOCAR_ROOT, \"datasets\", \"bdd100k_yolo\")\n",
    "\n",
    "# ── Load paths_config.yaml from notebook 01 (if available) ────────\n",
    "PATHS_CONFIG_FILE = os.path.join(ECOCAR_ROOT, \"paths_config.yaml\")\n",
    "paths_config = {}\n",
    "if os.path.isfile(PATHS_CONFIG_FILE):\n",
    "    with open(PATHS_CONFIG_FILE, 'r') as f:\n",
    "        paths_config = yaml.safe_load(f) or {}\n",
    "    print(f\"✅ Loaded paths_config.yaml from notebook 01\")\n",
    "    for k, v in paths_config.items():\n",
    "        print(f\"   {k}: {v}\")\n",
    "else:\n",
    "    print(f\"⚠️ paths_config.yaml not found at {PATHS_CONFIG_FILE}\")\n",
    "    print(f\"   Will use auto-detection for paths.\")\n",
    "\n",
    "# ── Debug mode ─────────────────────────────────────────────────────\n",
    "# Set to a small number (e.g., 100) for quick testing, or None for full dataset\n",
    "DEBUG_LIMIT = None  # Change to 100 for fast debugging\n",
    "\n",
    "if DEBUG_LIMIT:\n",
    "    print(f\"⚡ DEBUG MODE: Processing only {DEBUG_LIMIT} images\")\n",
    "\n",
    "print(f\"\\nRaw BDD dir:     {BDD_RAW_DIR}\")\n",
    "print(f\"YOLO dataset:    {YOLO_DATASET_DIR}\")",
]
clear_cell(nb02['cells'][5])

# --- Fix Cell 10: Locate BDD100K Files - use config + better search ---
nb02['cells'][10]['source'] = [
    "import glob\n",
    "\n",
    "# ── Try loading paths from paths_config.yaml first ────────────────\n",
    "TRAIN_LABEL = (\n",
    "    paths_config.get('train_labels_json')\n",
    "    or paths_config.get('train_label_path')\n",
    ")\n",
    "VAL_LABEL = paths_config.get('val_labels_json')\n",
    "\n",
    "# If only train path in config, infer val path\n",
    "if not VAL_LABEL and TRAIN_LABEL:\n",
    "    inferred_val = TRAIN_LABEL.replace('train', 'val')\n",
    "    if os.path.isfile(inferred_val):\n",
    "        VAL_LABEL = inferred_val\n",
    "\n",
    "# Validate config paths actually exist\n",
    "if TRAIN_LABEL and not os.path.isfile(TRAIN_LABEL):\n",
    "    print(f\"⚠️ paths_config train label not found: {TRAIN_LABEL}\")\n",
    "    TRAIN_LABEL = None\n",
    "if VAL_LABEL and not os.path.isfile(VAL_LABEL):\n",
    "    print(f\"⚠️ paths_config val label not found: {VAL_LABEL}\")\n",
    "    VAL_LABEL = None\n",
    "\n",
    "# ── Auto-detect label paths (fallback) ─────────────────────────────\n",
    "if not TRAIN_LABEL or not VAL_LABEL:\n",
    "    label_search_paths = [\n",
    "        # v1 format (generated by notebook 01)\n",
    "        os.path.join(BDD_RAW_DIR, \"labels\", \"bdd100k_labels_images_train.json\"),\n",
    "        os.path.join(BDD_RAW_DIR, \"labels\", \"bdd100k_labels_images_val.json\"),\n",
    "        # det_20 format (newer BDD100K releases)\n",
    "        os.path.join(BDD_RAW_DIR, \"bdd100k\", \"labels\", \"det_20\", \"det_train.json\"),\n",
    "        os.path.join(BDD_RAW_DIR, \"bdd100k\", \"labels\", \"det_20\", \"det_val.json\"),\n",
    "        # Direct labels dir\n",
    "        os.path.join(BDD_RAW_DIR, \"labels\", \"det_20\", \"det_train.json\"),\n",
    "        os.path.join(BDD_RAW_DIR, \"labels\", \"det_20\", \"det_val.json\"),\n",
    "        # bdd100k sub-directory v1 format\n",
    "        os.path.join(BDD_RAW_DIR, \"bdd100k\", \"labels\", \"bdd100k_labels_images_train.json\"),\n",
    "        os.path.join(BDD_RAW_DIR, \"bdd100k\", \"labels\", \"bdd100k_labels_images_val.json\"),\n",
    "    ]\n",
    "\n",
    "    for p in label_search_paths:\n",
    "        if os.path.isfile(p):\n",
    "            if 'train' in os.path.basename(p) and not TRAIN_LABEL:\n",
    "                TRAIN_LABEL = p\n",
    "            elif 'val' in os.path.basename(p) and not VAL_LABEL:\n",
    "                VAL_LABEL = p\n",
    "\n",
    "# ── Resolve image directories ─────────────────────────────────────\n",
    "# Try paths_config first\n",
    "TRAIN_IMAGES_DIR = paths_config.get('train_images_dir')\n",
    "VAL_IMAGES_DIR   = paths_config.get('val_images_dir')\n",
    "\n",
    "# Validate\n",
    "if TRAIN_IMAGES_DIR and not os.path.isdir(TRAIN_IMAGES_DIR):\n",
    "    print(f\"⚠️ paths_config train_images_dir not found: {TRAIN_IMAGES_DIR}\")\n",
    "    TRAIN_IMAGES_DIR = None\n",
    "if VAL_IMAGES_DIR and not os.path.isdir(VAL_IMAGES_DIR):\n",
    "    print(f\"⚠️ paths_config val_images_dir not found: {VAL_IMAGES_DIR}\")\n",
    "    VAL_IMAGES_DIR = None\n",
    "\n",
    "# Fallback: auto-detect image base directory\n",
    "if not TRAIN_IMAGES_DIR or not VAL_IMAGES_DIR:\n",
    "    img_search = [\n",
    "        os.path.join(BDD_RAW_DIR, \"bdd100k\", \"images\", \"100k\"),\n",
    "        os.path.join(BDD_RAW_DIR, \"images\", \"100k\"),\n",
    "        os.path.join(BDD_RAW_DIR, \"100k\"),                 # actual layout from extraction\n",
    "        \"/content/bdd100k_images/100k\",                     # local symlinks from notebook 01\n",
    "    ]\n",
    "    for p in img_search:\n",
    "        if os.path.isdir(p):\n",
    "            # Check if train/val subdirs exist\n",
    "            if os.path.isdir(os.path.join(p, 'train')):\n",
    "                if not TRAIN_IMAGES_DIR:\n",
    "                    TRAIN_IMAGES_DIR = os.path.join(p, 'train')\n",
    "                if not VAL_IMAGES_DIR:\n",
    "                    val_sub = os.path.join(p, 'val')\n",
    "                    VAL_IMAGES_DIR = val_sub if os.path.isdir(val_sub) else os.path.join(p, 'train')\n",
    "                break\n",
    "\n",
    "# ── Print summary ─────────────────────────────────────────────────\n",
    "print(f\"Train labels: {TRAIN_LABEL}\")\n",
    "print(f\"Val labels:   {VAL_LABEL}\")\n",
    "print(f\"Train images: {TRAIN_IMAGES_DIR}\")\n",
    "print(f\"Val images:   {VAL_IMAGES_DIR}\")\n",
    "\n",
    "if not all([TRAIN_LABEL, VAL_LABEL, TRAIN_IMAGES_DIR]):\n",
    "    print(\"\\n❌ Could not auto-detect all paths.\")\n",
    "    print(\"   Please ensure notebook 01 ran successfully, or set paths manually:\")\n",
    "    print('   TRAIN_LABEL = \"...\"')\n",
    "    print('   VAL_LABEL = \"...\"')\n",
    "    print('   TRAIN_IMAGES_DIR = \"...\"')\n",
    "    print('   VAL_IMAGES_DIR = \"...\"')\n",
    "else:\n",
    "    print(\"\\n✅ All paths detected successfully!\")",
]
clear_cell(nb02['cells'][10])

# --- Fix Cell 13: Convert train labels - add guard ---
nb02['cells'][13]['source'] = [
    "# Convert train labels\n",
    "if TRAIN_LABEL is None:\n",
    "    raise FileNotFoundError(\n",
    "        \"TRAIN_LABEL is None — label JSON not found.\\n\"\n",
    "        \"Please run notebook 01 first, or set TRAIN_LABEL manually in Section 4.\"\n",
    "    )\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\" Converting TRAIN labels\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "train_counts = convert_bdd100k_to_yolo(\n",
    "    json_path=TRAIN_LABEL,\n",
    "    output_label_dir=os.path.join(YOLO_DATASET_DIR, 'labels', 'train'),\n",
    "    debug_limit=DEBUG_LIMIT,\n",
    ")\n",
    "\n",
    "print(\"\\nTrain class distribution:\")\n",
    "print_class_distribution(train_counts)",
]
clear_cell(nb02['cells'][13])

# --- Fix Cell 14: Convert val labels - add guard ---
nb02['cells'][14]['source'] = [
    "# Convert val labels\n",
    "if VAL_LABEL is None:\n",
    "    raise FileNotFoundError(\n",
    "        \"VAL_LABEL is None — label JSON not found.\\n\"\n",
    "        \"Please run notebook 01 first, or set VAL_LABEL manually in Section 4.\"\n",
    "    )\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\" Converting VAL labels\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "val_counts = convert_bdd100k_to_yolo(\n",
    "    json_path=VAL_LABEL,\n",
    "    output_label_dir=os.path.join(YOLO_DATASET_DIR, 'labels', 'val'),\n",
    "    debug_limit=DEBUG_LIMIT,\n",
    ")\n",
    "\n",
    "print(\"\\nVal class distribution:\")\n",
    "print_class_distribution(val_counts)",
]
clear_cell(nb02['cells'][14])

# --- Fix Cell 16: Link train images - use TRAIN_IMAGES_DIR ---
nb02['cells'][16]['source'] = [
    "# Link (or copy) train images\n",
    "if TRAIN_IMAGES_DIR is None:\n",
    "    raise FileNotFoundError(\n",
    "        \"TRAIN_IMAGES_DIR is None — image directory not found.\\n\"\n",
    "        \"Please run notebook 01 first, or set TRAIN_IMAGES_DIR manually in Section 4.\"\n",
    "    )\n",
    "\n",
    "train_img_dst = os.path.join(YOLO_DATASET_DIR, 'images', 'train')\n",
    "\n",
    "print(f\"Linking train images: {TRAIN_IMAGES_DIR} → {train_img_dst}\")\n",
    "n_train = link_or_copy_images(\n",
    "    TRAIN_IMAGES_DIR, train_img_dst,\n",
    "    use_symlinks=True,\n",
    "    debug_limit=DEBUG_LIMIT,\n",
    ")\n",
    "print(f\"✅ {n_train} train images linked\")",
]
clear_cell(nb02['cells'][16])

# --- Fix Cell 17: Link val images - use VAL_IMAGES_DIR ---
nb02['cells'][17]['source'] = [
    "# Link (or copy) val images\n",
    "if VAL_IMAGES_DIR is None:\n",
    "    print(\"⚠️ VAL_IMAGES_DIR is None — using train images dir as fallback.\")\n",
    "    print(\"   (Notebook 01 may have put all images in one folder.)\")\n",
    "    VAL_IMAGES_DIR = TRAIN_IMAGES_DIR\n",
    "\n",
    "val_img_dst = os.path.join(YOLO_DATASET_DIR, 'images', 'val')\n",
    "\n",
    "print(f\"Linking val images: {VAL_IMAGES_DIR} → {val_img_dst}\")\n",
    "n_val = link_or_copy_images(\n",
    "    VAL_IMAGES_DIR, val_img_dst,\n",
    "    use_symlinks=True,\n",
    "    debug_limit=DEBUG_LIMIT,\n",
    ")\n",
    "print(f\"✅ {n_val} val images linked\")",
]
clear_cell(nb02['cells'][17])

with open(nb02_path, 'w', encoding='utf-8') as f:
    json.dump(nb02, f, ensure_ascii=False)
print(f"✅ Updated: {nb02_path}")


# ============================================================
# PART 2: Add markdown cells to 01_dataset_setup_and_download.ipynb
# ============================================================
nb01_path = os.path.join(BASE, "01_dataset_setup_and_download.ipynb")
with open(nb01_path, 'r', encoding='utf-8') as f:
    nb01 = json.load(f)

# After "## 6 — Verify Files Exist" (index 12), there are 4 code cells
# at indices [13], [14], [15], [16] that lack markdown explanations.

md_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.1 — Create Symlinks & Inspect Label Format\n",
            "\n",
            "BDD100K images extracted to `bdd100k_raw/100k/train/`, but downstream notebooks expect `bdd100k_raw/bdd100k/images/100k/{train,val}/`. We bridge this with **symlinks** instead of copying ~6 GB of data.\n",
            "\n",
            "We also peek at a sample per-image JSON to understand the **Scalabel** annotation format — BDD100K's native format uses `frames[0].objects` with `box2d` (bounding boxes) and `poly2d` (lane polylines).",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.2 — Preview Raw Label JSON Structure\n",
            "\n",
            "Pretty-print one per-image Scalabel JSON to verify the format before merging. Each file contains:\n",
            "- `name` — image stem (e.g. `4b78e751-af8b04dc`)\n",
            "- `frames[0].objects[]` — annotations with `category`, `box2d`, and optionally `poly2d`",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.3 — Merge Per-Image Labels → Combined Train/Val JSON\n",
            "\n",
            "BDD100K ships **70K individual JSON files** (one per image in Scalabel format), but notebook 02 expects a single combined JSON (a list of frames with `name` and `labels` keys).\n",
            "\n",
            "This cell:\n",
            "1. Reads each per-image JSON and re-maps `frames[0].objects` → flat `labels` list\n",
            "2. Keeps both `box2d` (detection) and `poly2d` (lane) annotations\n",
            "3. Filters to images that have a matching `.jpg`\n",
            "4. Shuffles and splits **85 / 15** into `bdd100k_labels_images_train.json` and `bdd100k_labels_images_val.json`\n",
            "\n",
            "> ⚠️ This takes ~3 minutes on Colab (reading 20K JSON files from Drive).",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.4 — Local Symlinks & Save Paths Configuration\n",
            "\n",
            "Google Drive symlinks can be unreliable in Colab, so we create **local** symlinks at `/content/bdd100k_images/100k/{train,val}` pointing to the Drive image folder.\n",
            "\n",
            "A `paths_config.yaml` is saved to Drive with all resolved paths (image dirs + label JSONs) so that **notebook 02 and later notebooks can load paths automatically** without re-detecting.",
        ],
    },
]

# Insert in reverse order to preserve indices
for i in reversed(range(len(md_cells))):
    insert_idx = 13 + i
    nb01['cells'].insert(insert_idx, md_cells[i])

with open(nb01_path, 'w', encoding='utf-8') as f:
    json.dump(nb01, f, ensure_ascii=False)
print(f"✅ Updated: {nb01_path}")

print("\n🎯 Both notebooks updated successfully!")
